number1 = int(input("fill first number"))
number2 = int(input("fill second number"))
print(number1, "+", number2, "=", number1+number2)
print(number1, "-", number2, "=", number1-number2)
print(number1, "*", number2, "=", number1*number2)
print(number1, "/", number2, "=", int(number1/number2))